packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  esbuild: true

engineStrict: true
injectWorkspacePackages: true
nodeVersion: 24.14.0
preferWorkspacePackages: true
savePrefix: ''
